### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [le3mon/send-arp#1]
https://github.com/le3mon/send-arp/commit/f4848a76c29187e3bc3580afe06a58f691579763#r38575783

https://github.com/le3mon/send-arp/commit/f4848a76c29187e3bc3580afe06a58f691579763#r38575787

https://github.com/le3mon/send-arp/commit/f4848a76c29187e3bc3580afe06a58f691579763#r38575793

https://github.com/le3mon/send-arp/commit/f4848a76c29187e3bc3580afe06a58f691579763#r38575816

**Comment by le3mon** [comment]
https://github.com/le3mon/send-arp/commit/a9bef9f61f3dad1d69382010938d27426f5c7f95

**Comment by snoopspy** [comment]
수고하셨습니다.
